// <auto-generated />
namespace MUE.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_summ_toServiceBill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_summ_toServiceBill));
        
        string IMigrationMetadata.Id
        {
            get { return "202001311935589_add_summ_toServiceBill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
